
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import chrriis.dj.nativeswing.NativeSwing;
import java.awt.BorderLayout;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Angelina Santana
 */
public class navegador extends javax.swing.JInternalFrame {

    /**
     * Creates new form navegador
     */
    
    JWebBrowser navegador = new JWebBrowser();
    
    public navegador() {
        initComponents();
        
        this.web_panel.setLayout(new BorderLayout());
        navegador.navigate("https://www.google.com");
        this.web_panel.add(navegador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        web_panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("NAVEGADOR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        web_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(web_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel web_panel;
    // End of variables declaration//GEN-END:variables
}
